version: '3.8'

services:
  janus:
    image: canyan/janus-gateway:latest
    container_name: janus-gateway
    ports:
      - "8088:8088"  # HTTP API
      - "8089:8089"  # HTTPS API (optional)
      - "8188:8188"  # WebSocket
      - "8989:8989"  # Admin API (optional)
      - "7088:7088"  # SIP (optional)
      - "5002:5002"  # RTP
      - "5004:5004"  # RTP
    environment:
      - DOCKER_IP=${DOCKER_IP:-192.168.200.106}
    volumes:
      - ./janus-config:/usr/local/etc/janus
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    restart: unless-stopped
    networks:
      - mini-area-network

networks:
  mini-area-network:
    driver: bridge